# This file was generated by GoReleaser. DO NOT EDIT.
cask "achta" do
  version "0.5.12"

  on_macos do
    on_intel do
      sha256 "bd9ec7c6861c95fb6cce679320884db3087c24eba39bb9bc021299528c9158d2"
      url "https://github.com/ozgurcd/achta/releases/download/v#{version}/achta_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "cbff274eebf21f0b9ecc5a812fac213a5fe2e21979ac1c64582b14b97a27ffd8"
      url "https://github.com/ozgurcd/achta/releases/download/v#{version}/achta_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "95d779bef0873f4d2b371e367e96875082dbfc73cff9aa9a6161b6efbe32943a"
      url "https://github.com/ozgurcd/achta/releases/download/v#{version}/achta_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "beb4e8d31f29634f8640be61fa6579ac8bb6ea8f5a03a22dd501e5f0013e8527"
      url "https://github.com/ozgurcd/achta/releases/download/v#{version}/achta_Linux_arm64.tar.gz"
    end
  end

  name "achta"
  desc "Fail-closed workspace bookkeeping for Identuum repositories"
  homepage "https://github.com/ozgurcd/achta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "achta"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/achta"]
    end
  end

  # No zap stanza required

end
