# This file was generated by GoReleaser. DO NOT EDIT.
cask "achta" do
  version "0.4.4"

  on_macos do
    on_intel do
      sha256 "af33f5f02c600d48aab6cd5757ed97f4511feae8ba319f80c620f68e73b7890c"
      url "https://api.github.com/repos/ozgurcd/achta/releases/assets/546226148",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}",
        ]
    end
    on_arm do
      sha256 "cef309af2ecd0b15a9f94abcd8f942b55380616118374a83a8a8e713cd79a7c6"
      url "https://api.github.com/repos/ozgurcd/achta/releases/assets/546226150",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}",
        ]
    end
  end

  on_linux do
    on_intel do
      sha256 "efc3e8a90fbb60419a654395ff96bbec87b154a1a4f6b69e735ca796a1c98f90"
      url "https://api.github.com/repos/ozgurcd/achta/releases/assets/546226172",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}",
        ]
    end
    on_arm do
      sha256 "ee087c5cc8183ba02faf25b1c9dd05dd120c5d2e2e8aa9198dcf83d67f0cfb83"
      url "https://api.github.com/repos/ozgurcd/achta/releases/assets/546226169",
        header: [
          "Accept: application/octet-stream",
          "Authorization: Bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}",
        ]
    end
  end

  name "achta"
  desc "Fail-closed workspace bookkeeping for Identuum repositories"
  homepage "https://github.com/ozgurcd/achta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "achta"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/achta"]
    end
  end

  # No zap stanza required

end
