# This file was generated by GoReleaser. DO NOT EDIT.
cask "achta" do
  version "0.5.17"

  on_macos do
    on_intel do
      sha256 "ea120560a3c2ff4fe9c08e93790256c2e8c5d7247ddfffca317fc76d24c7b7b4"
      url "https://github.com/ozgurcd/achta/releases/download/v#{version}/achta_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1c16a4edf2d9f9464df4377848a276d00d6967bf32956918c7a66bd2d1227f21"
      url "https://github.com/ozgurcd/achta/releases/download/v#{version}/achta_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3fd1c585dc168b571363435a688b7c656b97415e8fc8d7774b179fee4bac964e"
      url "https://github.com/ozgurcd/achta/releases/download/v#{version}/achta_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0ea12f24fba9cdf19fee045bd561f3bb550ca0acacfd9c2f3c9680374501e2e6"
      url "https://github.com/ozgurcd/achta/releases/download/v#{version}/achta_Linux_arm64.tar.gz"
    end
  end

  name "achta"
  desc "Fail-closed workspace bookkeeping for Identuum repositories"
  homepage "https://github.com/ozgurcd/achta"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "achta"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/achta"]
    end
  end

  # No zap stanza required

end
