# This file was generated by GoReleaser. DO NOT EDIT.
cask "gograph" do
  version "1.7.12"

  on_macos do
    on_intel do
      sha256 "aab1d96e2b9dd44b8768a036d0a7ab42e517c90716396b5a48273ab67a328b72"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "583323dcbbb0d2b9ed95d2434ab5a6dfe69fda6b2446d2cae9bca886e7f2b2a6"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd0c0eece57de1a9b433881d8352f607266bb1451e4e49b5e480d9fbda806f62"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fc40e2b373b8e11b1167c2efd2e735a4516be760e80c0316646fe3ec34fcc153"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Linux_arm64.tar.gz"
    end
  end

  name "gograph"
  desc "Fast, AST-based repository structure and call graph analyzer for Go"
  homepage "https://github.com/ozgurcd/gograph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gograph"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/gograph"]
    end
  end

  # No zap stanza required

end
