# This file was generated by GoReleaser. DO NOT EDIT.
cask "gograph" do
  version "1.6.8"

  on_macos do
    on_intel do
      sha256 "72fe8c814ae525b08e105d8039df716423f834eb3a1a9c29f93ad0c74c994d77"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4ff9e52ffc6960b23b38424790d02f429869fbd7d5bbb9cb7836afaf57cad315"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e571f1017f5ab4002335026d0d882ece8973be511e625664be683a16be5f7bea"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "38f62d256b969166e2652522d6e079e73516d9e38728a7b0d50f3d6dcfc944fc"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Linux_arm64.tar.gz"
    end
  end

  name "gograph"
  desc "Fast, AST-based repository structure and call graph analyzer for Go"
  homepage "https://github.com/ozgurcd/gograph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gograph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gograph"]
    end
  end

  # No zap stanza required

end
