# This file was generated by GoReleaser. DO NOT EDIT.
cask "gograph" do
  version "1.6.6"

  on_macos do
    on_intel do
      sha256 "71c24782e79ecebb3e56a75fce1812f250202f52b4b3fe5dfa8cdc5fd1e74358"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f6cb01eec13785376c7856603947b880c9242623bd44264059f53b264126d269"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5e90abe7274a339084bbfc9e867883ccebe3c8453c7c0b24be440332d6725a27"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "79b385f3f057ac92116dad244b87f190431ad254a77ee3e69a6ef0bd63d0bc4e"
      url "https://github.com/ozgurcd/gograph/releases/download/v#{version}/gograph_Linux_arm64.tar.gz"
    end
  end

  name "gograph"
  desc "Fast, AST-based repository structure and call graph analyzer for Go"
  homepage "https://github.com/ozgurcd/gograph"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gograph"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gograph"]
    end
  end

  # No zap stanza required

end
