# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuntius" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "0208e5c5a44fe40d4b48c21bd055208b9b09c046757b04c9d289616b1b04a8d4"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1bb50f190e3f6e8409f116b428281c72d3c96a72dd816c695bec1350399d0571"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "df74ee03987be812ef360a4963a76852be7a2d46b7b493e423a72d1c6bcfe556"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ad4784255b147088905adb5a12eb8666c62f209ebddb3a5cc60ef9273965e504"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Linux_arm64.tar.gz"
    end
  end

  name "nuntius"
  desc "Local MCP run manager for the judge in Claude Desktop"
  homepage "https://github.com/ozgurcd/nuntius"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuntius"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nuntius"]
    end
  end

  # No zap stanza required

end
