# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuntius" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "53a1c722dd9d1b05ec01ddd0fe0f3fa07fac6d836502659dec2a17c4291e4914"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9f318834961e72aaebc3d81aa3c15d83295c842c52f2ae0174bf18cb88a79061"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7138f1b08ace8fe97378596c08b3d80ec0545d63a6a4129ed96f16b6ef3906da"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "336a26bc3a7c1f53b7193d7a0ebe064dfa08625c902e8cb8b5c1ea2490722bde"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Linux_arm64.tar.gz"
    end
  end

  name "nuntius"
  desc "Local MCP run manager for the judge in Claude Desktop"
  homepage "https://github.com/ozgurcd/nuntius"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuntius"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nuntius"]
    end
  end

  # No zap stanza required

end
