# This file was generated by GoReleaser. DO NOT EDIT.
cask "nuntius" do
  on_macos do
    app "Nuntius Menu Bar.app"
    binary "#{appdir}/Nuntius Menu Bar.app/Contents/MacOS/nuntius-menubar", target: "nuntius-menubar"
  end
  on_linux do
    binary "nuntius-menubar"
  end

  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "26087460a6552a3243a0d9661e4eccd30d72228b1de4087196634d6b80073051"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e7a1d0ab6126e32ea57492286cb9a98e869068d28065bf052fac583e7c7d4187"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3584230bca6642b5e5e246f58168eee41f2aa3d5c5c2e6280ff71fbdda7dfdc5"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e66235dd503c207297334965b207670b2deabea3bbfebeef90d8f4fd35628ce8"
      url "https://github.com/ozgurcd/nuntius/releases/download/v#{version}/nuntius_Linux_arm64.tar.gz"
    end
  end

  name "nuntius"
  desc "Local MCP run manager for the judge in Claude Desktop"
  homepage "https://github.com/ozgurcd/nuntius"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nuntius"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nuntius"]
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/nuntius-menubar"]
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/Nuntius Menu Bar.app"]
    end
  end

  # No zap stanza required

end
