# This file was generated by GoReleaser. DO NOT EDIT.
cask "scrinium" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "6ca1ceb65b58b647210182e10c7c488b3d7611049ef4d8b454b88db00d7ea02f"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "85be5712f813e2ffb11bfc099f22d1e5c254de883e9278019c7a1c17c9f5a796"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "78ad41f7d95fdb032f0990ce472c83f7481364f3636611098015bdabea3a111c"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ef612106dd35d55ea74a5a270fa58275cdfd82235e688ea0117150b492f2161"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scrinium"
  desc "Governed wiki MCP server for AI coding agents"
  homepage "https://github.com/ozgurcd/scrinium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scrinium"

  # No zap stanza required

end
