# This file was generated by GoReleaser. DO NOT EDIT.
cask "scrinium" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "523ff226d45c9348ef60906fa2710e599018a88d85185b6b80125febee90914f"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5df4e3000596a094e0498945bbc15a1c224574550e33e2811ba035ccbc4978e5"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a48d12c44eb263a8494687a4087756899f22065de0bfa01d3913a08a80453af"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c491f69a216868b16d215835726b3421a80ea4342ecedead87f1bbc21f1e54e"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scrinium"
  desc "Governed wiki MCP server for AI coding agents"
  homepage "https://github.com/ozgurcd/scrinium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scrinium"

  # No zap stanza required

end
