# This file was generated by GoReleaser. DO NOT EDIT.
cask "scrinium" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "d9c72342bcc36cd0cd66991479444e37b1c578082d020b85b2973419ddac7b16"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6029ce673d362f4d42323a00344860164eb387d8aa42a95328e7d0aa89ee85cd"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fc93fe136fcabbedfb41437f56be679e201c23b2de718b2f406339a28ea3eb0b"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4797c65b179214758310d950aa550af66ba67012909c1db8c778da988502497d"
      url "https://github.com/ozgurcd/scrinium/releases/download/v#{version}/scrinium_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scrinium"
  desc "Governed wiki MCP server for AI coding agents"
  homepage "https://github.com/ozgurcd/scrinium"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scrinium"

  # No zap stanza required

end
