# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gograph < Formula
  desc "A fast, AST-based repository structure and call graph analyzer for Go."
  homepage "https://github.com/ozgurcd/gograph"
  version "1.4.52"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ozgurcd/gograph/releases/download/v1.4.52/gograph_Darwin_x86_64.tar.gz"
      sha256 "b3a6023a2c27cb6d750b0ebb109cece4a2eb5218c43693183b51b8ae508a959a"

      define_method(:install) do
        bin.install "gograph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ozgurcd/gograph/releases/download/v1.4.52/gograph_Darwin_arm64.tar.gz"
      sha256 "bb48555d072ad0016b077bbf4898f854b818386f2c68a30975fe61b6a70e5d08"

      define_method(:install) do
        bin.install "gograph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ozgurcd/gograph/releases/download/v1.4.52/gograph_Linux_x86_64.tar.gz"
      sha256 "94e71e955ce4612a42007369050c794ec934e090447419983a94fdb632f6f16f"
      define_method(:install) do
        bin.install "gograph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ozgurcd/gograph/releases/download/v1.4.52/gograph_Linux_arm64.tar.gz"
      sha256 "691f613d51c41cce9645c5192f7cd017299e8863a8220adfac0d45d4a7c55a5e"
      define_method(:install) do
        bin.install "gograph"
      end
    end
  end

  test do
    system "#{bin}/gograph --version"
  end
end
